### PR TITLE
task 8 keyword filter applied after 3 chars

### PR DESCRIPTION
**Pull request by linama5**

### CODE REVIEW

**Review by christerresin — APPROVED** [review]
Nice and small fix!

**Review by matodorovic — APPROVED** [review]
Nice 👍

**Review by amyrman — APPROVED** [review]
Yeah, short and sweet fix! Good job! 👏 🙌

**Review by matodorovic — CHANGES_REQUESTED** [review]
There is some conflict with sorting. Could u take a look at it?

**Review by aamin75 — APPROVED** [review]
Good job Lina
Tested and approved

**Review by matodorovic — APPROVED** [review]

**Comment by matodorovic** [comment]
Since there are 4 approvals I merge it into main.

**Pull request merged**
