### PR TITLE
20. Color change from darkblue to #021928

### PR DESCRIPTION
**Pull request by matodorovic**
Changed color #011827 to #021928

### CODE REVIEW

**Review by aamin75 — COMMENTED** [review]
Work done perfectly

**Review by aamin75 — APPROVED** [review]
Done perfectly

**Review by christerresin — APPROVED** [review]
Looks great!

**Review by amyrman — APPROVED** [review]
Looks good!

**Review by linama5 — APPROVED** [review]
Good :)

**Pull request merged**
