### PR TITLE
21. Lägg till “Om oss”-sidan

### PR DESCRIPTION
**Pull request by matodorovic**
I added story.html och some css. In Trello is avaliable Figma project of the site and screenshot.

### CODE REVIEW

**Review by christerresin — APPROVED** [review]
Nice start

**Review by amyrman — APPROVED** [review]
Pulled and tested. Looks good and works smoothly! So functionality-wise it's all good to go. Just a couple of esthetical notes: the hover color is inverted on the "Contact me"-buttons, and -- for me at least -- the motto text is not vertically centered. This makes me thing that re-using same styling templates for similar elements would be cool.

**Comment by matodorovic** [comment]
> Pulled and tested. Looks good and works smoothly! So functionality-wise it's all good to go. Just a couple of esthetical notes: the hover color is inverted on the "Contact me"-buttons, and -- for me at least -- the motto text is not vertically centered. This makes me thing that re-using same styling templates for similar elements would be cool.

I change those things now so u can test it and tell me if it is okay.

**Review by aamin75 — COMMENTED** [review]
The appearance of the team cards in the responsive design is so wide comparing with the used images. 
Please review the main.css for this issue.

**Pull request merged**
