### PR TITLE
12. Hover-effekter på alla knappar och länkar

### PR DESCRIPTION
**Pull request by matodorovic**
Since most of it was already done I just added cursor pointer and change colors of hover but not visible to not differ the site's color choice.  I also added gray color for hover of filter button and changed color for X button to gray so it can hover som black.

### CODE REVIEW

**Review by christerresin — APPROVED** [review]
Great work!

**Comment by amyrman** [comment]
> change colors of hover but not visible to not differ the site's color choice.

Could you please clarify what's meant with "but not visible", thanks

**Comment by matodorovic** [comment]
> > change colors of hover but not visible to not differ the site's color choice.
> 
> Could you please clarify what's meant with "but not visible", thanks

I change it on a color which is similar to the one we use.

**Review by amyrman — APPROVED** [review]
Pulled, tested. Good job! */me stamps "Approved!"* 😄

**Pull request merged**
