### PR TITLE
9

### PR DESCRIPTION
**Pull request by christerresin**
New pull. Messed up and merged in "Sort" in the last commit.

### CODE REVIEW

**Review by aamin75 — APPROVED** [review]
Perfect job
Approved

**Review by matodorovic — APPROVED** [review]
Good job. 👍

**Comment by matodorovic** [comment]
I fetched 9 branch and saw ur changes. Looks nice :)

**Review by amyrman — APPROVED** [review]
Pulled the branch too for testing. Looks good!

Oh now I think I understand what went wrong. I was looking for the sorting functions this time but couldn't find them! And I shouldn't be able to, should I!? Lol.

The "shuffle fluff" has a good ring to it btw. 😄 I want us to keep it although links should point to on-site and online!

**Pull request merged**
