### PR TITLE
4

### PR DESCRIPTION
**Pull request by aamin75**
Challenge id has been added successfully to the GET method and to the POST method

### CODE REVIEW

**Review by matodorovic — APPROVED** [review]
Good job, Ammar

**Review by linama5 — APPROVED** [review]
Aproved

**Comment by amyrman** [comment]
Goodie!

As usual we get these conflicts because of the order of merging. Because phone number function was merged into main, now it needs to be pulled into this first and updated.

There ought to be some other automated way to solve it?

But anyway, after that, I think this can be merged.

**Review by amyrman — CHANGES_REQUESTED** [review]
As usual we get conflicts because of the order of merging. Because other things was merged into main, now main needs to be merged into 4 first, staged, commited, pushed.

There ought to be some other easier, maybe automated way, to solve it?

But anyway, after that, I think this can be merged. Nice job!

**Comment by aamin75** [comment]
I have fixed the previous conflict. The changes on the main after creating the branch have been included in this request.
Kindly review it and give your comments, otherwise merge it to the main.

**Pull request merged**
