### PR TITLE
13 - Add phone number input to booking

### PR DESCRIPTION
**Pull request by amyrman**
EDIT: Fixed now? Works on my end as far as I can tell.

Hey you guys, it's friday night! If anyone's looking at this now you should enjoy your evening instead!!

Anyway. Please review. ...and some things that might be good to jot down incase, I dunno...

Everything works on my end as far as I can tell. Pulled main just now and had some conflicts which I couldn't even make out with bundle.js, but didn't seem to cause any problems as bundle.js just gets rebuilt anyway as far as I know? I mean it doesn't actually change any source code?

Had a problem which I thought was with API but just I forgot to run npm watch once again so there's nothing wrong with booking API. I think we had a discussion about it.

**Some changes I didn't mention in commit msg's:**

Deleted TODO comments which were obsolete as far as I could tell.

Had a README on the branch to explain which feature it was for, which I deleted but forgot to include in commit message.

### CODE REVIEW

**Review by matodorovic — CHANGES_REQUESTED** [review]
There is an issue with sending.

**Review by aamin75 — APPROVED** [review]
Good job Anders.
There will be a merge conflict with the main due to several changes on the main and the gap between the branches updating. It isn't a big issue and easily solve.

**Comment by amyrman** [comment]
I tried the web editor here on GitHub to solve them.

**Review by matodorovic — APPROVED** [review]

**Review by matodorovic — APPROVED** [review]
Good job!

**Review by linama5 — APPROVED** [review]
Approved great !!!

**Comment by amyrman** [comment]
> There is an issue with sending.

Now the whole booking process + POST works on my end.

**Pull request merged**
